const slotsGames = {
  PG: [
    {
      id: 'PG',
      title: 'Midas Fortune',
      href: 'images/gameNavBg05-icon01-1.png',
    },
    {
      id: 'PG',
      title: 'Asgardian Rising',
      href: 'images/gameNavBg05-icon01-2.png',
    },
    {
      id: 'PG',
      title: 'Diner Delights',
      href: 'images/gameNavBg05-icon01-3.png',
    },
    {
      id: 'PG',
      title: 'Alchemy Gold',
      href: 'images/gameNavBg05-icon01-4.png',
    },
    {
      id: 'PG',
      title: 'Totem Wonders',
      href: 'images/gameNavBg05-icon01-5.png',
    },
    {
      id: 'PG',
      title: 'Prosperity Fortune Tree',
      href: 'images/gameNavBg05-icon01-6.png',
    },
    {
      id: 'PG',
      title: 'Wild Bounty Showdown',
      href: 'images/gameNavBg05-icon01-7.png',
    },
    {
      id: 'PG',
      title: 'Wild Coaster',
      href: 'images/gameNavBg05-icon01-8.png',
    },
    {
      id: 'PG',
      title: 'Legend of Perseus',
      href: 'images/gameNavBg05-icon01-9.png',
    },
    {
      id: 'PG',
      title: 'Speed Winner',
      href: 'images/gameNavBg05-icon01-10.png',
    },
  ],
  FC: [
    {
      id: 'FC',
      title: 'GOLDEN GENIE',
      href: 'images/gameNavBg05-icon02-1.png',
      freeTrial: true,
    },
    {
      id: 'FC',
      title: 'MERGE MAGIC',
      href: 'images/gameNavBg05-icon02-2.png',
      freeTrial: true,
    },
    {
      id: 'FC',
      title: 'CRAZY BUFFALO',
      href: 'images/gameNavBg05-icon02-3.png',
      freeTrial: true,
    },
    {
      id: 'FC',
      title: 'SUGAR BANG BANG',
      href: 'images/gameNavBg05-icon02-4.png',
      freeTrial: true,
    },
    {
      id: 'FC',
      title: 'Treasure Raiders',
      href: 'images/gameNavBg05-icon02-5.png',
      freeTrial: true,
    },
    {
      id: 'FC',
      title: 'Grand Blue',
      href: 'images/gameNavBg05-icon02-6.png',
      freeTrial: true,
    },
    {
      id: 'FC',
      title: 'Chinese New Year 2',
      href: 'images/gameNavBg05-icon02-7.png',
      freeTrial: true,
    },
    {
      id: 'FC',
      title: 'LUCKY FORTUNES',
      href: 'images/gameNavBg05-icon02-8.png',
      freeTrial: true,
    },
    {
      id: 'FC',
      title: 'ROBIN HOOD',
      href: 'images/gameNavBg05-icon02-9.png',
      freeTrial: true,
    },
    {
      id: 'FC',
      title: 'GOLD RUSH',
      href: 'images/gameNavBg05-icon02-10.png',
      freeTrial: true,
    },
  ],
  JL: [
    {
      id: 'JL',
      title: 'Neko Fortune',
      href: 'images/gameNavBg05-icon03-1.png',
    },
    {
      id: 'JL',
      title: 'Agent Ace',
      href: 'images/gameNavBg05-icon03-2.png',
    },
    {
      id: 'JL',
      title: 'Party Night',
      href: 'images/gameNavBg05-icon03-3.png',
    },
    {
      id: 'JL',
      title: 'Magic Lamp',
      href: 'images/gameNavBg05-icon03-4.png',
    },
    {
      id: 'JL',
      title: 'TwinWins',
      href: 'images/gameNavBg05-icon03-5.png',
    },
    {
      id: 'JL',
      title: 'Calaca Bingo',
      href: 'images/gameNavBg05-icon03-6.png',
    },
    {
      id: 'JL',
      title: 'Samba',
      href: 'images/gameNavBg05-icon03-7.png',
    },
    {
      id: 'JL',
      title: 'Ali Baba',
      href: 'images/gameNavBg05-icon03-8.png',
    },
    {
      id: 'JL',
      title: 'Mega Ace',
      href: 'images/gameNavBg05-icon03-9.png',
    },
    {
      id: 'JL',
      title: 'World Cup',
      href: 'images/gameNavBg05-icon03-10.png',
    },
  ],
  BNG: [
    {
      id: 'BNG',
      title: 'Tiger Jungle',
      href: 'images/gameNavBg05-icon04-1.png',
      freeTrial: true,
    },
    {
      id: 'BNG',
      title: 'Hit the Gold!',
      href: 'images/gameNavBg05-icon04-2.png',
      freeTrial: true,
    },
    {
      id: 'BNG',
      title: 'Sun of Egypt 3',
      href: 'images/gameNavBg05-icon04-3.png',
      freeTrial: true,
    },
    {
      id: 'BNG',
      title: 'Aztec Fire-Hold & win',
      href: 'images/gameNavBg05-icon04-4.png',
      freeTrial: true,
    },
    {
      id: 'BNG',
      title: 'Caishen Wealth',
      href: 'images/gameNavBg05-icon04-5.png',
      freeTrial: true,
    },
    {
      id: 'BNG',
      title: 'Super Rich GOD',
      href: 'images/gameNavBg05-icon04-6.png',
      freeTrial: true,
    },
    {
      id: 'BNG',
      title: 'Gold Express',
      href: 'images/gameNavBg05-icon04-7.png',
      freeTrial: true,
    },
    {
      id: 'BNG',
      title: 'Black Wolf',
      href: 'images/gameNavBg05-icon04-8.png',
      freeTrial: true,
    },
    {
      id: 'BNG',
      title: 'Queen Of The Sun',
      href: 'images/gameNavBg05-icon04-9.png',
      freeTrial: true,
    },
    {
      id: 'BNG',
      title: 'Golden Dancing Lion',
      href: 'images/gameNavBg05-icon04-10.png',
      freeTrial: true,
    },
  ],
  JDB: [
    {
      id: 'JDB',
      title: 'CooCoo Farm',
      href: 'images/gameNavBg05-icon05-1.png',
      freeTrial: true,
    },
    {
      id: 'JDB',
      title: 'ELEMENTAL LINK WATER',
      href: 'images/gameNavBg05-icon05-2.png',
      freeTrial: true,
    },
    {
      id: 'JDB',
      title: 'Elemental Link Fire',
      href: 'images/gameNavBg05-icon05-3.png',
      freeTrial: true,
    },
    {
      id: 'JDB',
      title: 'Birds Party Deluxe',
      href: 'images/gameNavBg05-icon05-4.png',
      freeTrial: true,
    },
    {
      id: 'JDB',
      title: 'Lucky Color Game',
      href: 'images/gameNavBg05-icon05-5.png',
      freeTrial: true,
    },
    {
      id: 'JDB',
      title: 'Moneybags Man 2',
      href: 'images/gameNavBg05-icon05-6.png',
      freeTrial: true,
    },
    {
      id: 'JDB',
      title: 'TrumpCard',
      href: 'images/gameNavBg05-icon05-7.png',
      freeTrial: true,
    },
    {
      id: 'JDB',
      title: 'Fortune Neko',
      href: 'images/gameNavBg05-icon05-8.png',
      freeTrial: true,
    },
    {
      id: 'JDB',
      title: 'BookOfMystery',
      href: 'images/gameNavBg05-icon05-9.png',
      freeTrial: true,
    },
    {
      id: 'JDB',
      title: 'BbqBurger',
      href: 'images/gameNavBg05-icon05-10.png',
      freeTrial: true,
    },
  ],
  MGS: [
    {
      id: 'MGS',
      title: '9 Masks Of Fire',
      href: 'images/gameNavBg05-icon06-1.png',
      freeTrial: true,
    },
    {
      id: 'MGS',
      title: 'Hound Hotel',
      href: 'images/gameNavBg05-icon06-2.png',
      freeTrial: true,
    },
    {
      id: 'MGS',
      title: '108 Heroes Multiplier Fortunes',
      href: 'images/gameNavBg05-icon06-3.png',
      freeTrial: true,
    },
    {
      id: 'MGS',
      title: 'Masters of Olympus',
      href: 'images/gameNavBg05-icon06-4.png',
      freeTrial: true,
    },
    {
      id: 'MGS',
      title: 'WWE : Fortune Dragon',
      href: 'images/gameNavBg05-icon06-5.png',
      freeTrial: true,
    },
    {
      id: 'MGS',
      title: 'Tiger’s Ice',
      href: 'images/gameNavBg05-icon06-6.png',
      freeTrial: true,
    },
    {
      id: 'MGS',
      title: 'Playboy Wilds',
      href: 'images/gameNavBg05-icon06-7.png',
      freeTrial: true,
    },
    {
      id: 'MGS',
      title: '9 Mad Hats™',
      href: 'images/gameNavBg05-icon06-8.png',
      freeTrial: true,
    },
    {
      id: 'MGS',
      title: 'WWE : Clash of the Wilds',
      href: 'images/gameNavBg05-icon06-9.png',
      freeTrial: true,
    },
    {
      id: 'MGS',
      title: '9 Skulls Of Gold™',
      href: 'images/gameNavBg05-icon06-10.png',
      freeTrial: true,
    },
  ],
  MA: [
    {
      id: 'MA',
      title: 'JinPingMai II',
      href: 'images/gameNavBg05-icon07-1.png',
    },
    {
      id: 'MA',
      title: 'FengShen',
      href: 'images/gameNavBg05-icon07-2.png',
    },
    {
      id: 'MA',
      title: 'Three Kingdoms',
      href: 'images/gameNavBg05-icon07-3.png',
    },
    {
      id: 'MA',
      title: 'Water Margin',
      href: 'images/gameNavBg05-icon07-4.png',
    },
    {
      id: 'MA',
      title: 'GodOfWealth',
      href: 'images/gameNavBg05-icon07-5.png',
    },
    {
      id: 'MA',
      title: 'HighWay King',
      href: 'images/gameNavBg05-icon07-6.png',
    },
    {
      id: 'MA',
      title: 'Thai Paradise',
      href: 'images/gameNavBg05-icon07-7.png',
    },
    {
      id: 'MA',
      title: 'SAFARI Heat',
      href: 'images/gameNavBg05-icon07-8.png',
    },
    {
      id: 'MA',
      title: 'Wealth’s Treasure',
      href: 'images/gameNavBg05-icon07-9.png',
    },
    {
      id: 'MA',
      title: 'Aztac',
      href: 'images/gameNavBg05-icon07-10.png',
    },
  ],
  BOM: [
    {
      id: 'BOM',
      title: 'The Jungle Empire',
      href: 'images/gameNavBg05-icon08-1.png',
      freeTrial: true,
    },
    {
      id: 'BOM',
      title: 'Let it Spin',
      href: 'images/gameNavBg05-icon08-2.png',
    },
    {
      id: 'BOM',
      title: 'Starlight Riches',
      href: 'images/gameNavBg05-icon08-3.png',
    },
    {
      id: 'BOM',
      title: 'The Rodfather Megaways',
      href: 'images/gameNavBg05-icon08-4.png',
    },
    {
      id: 'BOM',
      title: 'Dice Dice Baby',
      href: 'images/gameNavBg05-icon08-5.png',
    },
    {
      id: 'BOM',
      title: 'Crack the Bank Hold and Win',
      href: 'images/gameNavBg05-icon08-6.png',
    },
    {
      id: 'BOM',
      title: 'The Wild Wings of Phoenix',
      href: 'images/gameNavBg05-icon08-7.png',
    },
    {
      id: 'BOM',
      title: 'Hooked',
      href: 'images/gameNavBg05-icon08-8.png',
    },
    {
      id: 'BOM',
      title: 'Danger Zone',
      href: 'images/gameNavBg05-icon08-9.png',
    },
    {
      id: 'BOM',
      title: 'Show Master',
      href: 'images/gameNavBg05-icon08-10.png',
    },
  ],
  CQ9: [
    {
      id: 'CQ9',
      title: 'Mummy’s Treasure',
      href: 'images/gameNavBg05-icon09-1.png',
    },
    {
      id: 'CQ9',
      title: 'The Dragon Brings Wealth 2',
      href: 'images/gameNavBg05-icon09-2.png',
    },
    {
      id: 'CQ9',
      title: 'Sweet 666 Deluxe',
      href: 'images/gameNavBg05-icon09-3.png',
    },
    {
      id: 'CQ9',
      title: 'The Chicken House',
      href: 'images/gameNavBg05-icon09-4.png',
    },
    {
      id: 'CQ9',
      title: 'Royal Fruit',
      href: 'images/gameNavBg05-icon09-5.png',
    },
    {
      id: 'CQ9',
      title: 'Double Happiness',
      href: 'images/gameNavBg05-icon09-6.png',
    },
    {
      id: 'CQ9',
      title: 'Striker WILD',
      href: 'images/gameNavBg05-icon09-7.png',
    },
    {
      id: 'CQ9',
      title: 'Football Fever M',
      href: 'images/gameNavBg05-icon09-8.png',
    },
    {
      id: 'CQ9',
      title: 'Baseball Fever',
      href: 'images/gameNavBg05-icon09-9.png',
    },
    {
      id: 'CQ9',
      title: 'Myeong-ryang',
      href: 'images/gameNavBg05-icon09-10.png',
    },
  ],
  PNG: [
    {
      id: 'PNG',
      title: 'Cash-a-Cabana',
      href: 'images/gameNavBg05-icon10-1.png',
      freeTrial: true,
    },
    {
      id: 'PNG',
      title: 'Shamrock Miner',
      href: 'images/gameNavBg05-icon10-2.png',
      freeTrial: true,
    },
    {
      id: 'PNG',
      title: 'Wild Falls',
      href: 'images/gameNavBg05-icon10-3.png',
      freeTrial: true,
    },
    {
      id: 'PNG',
      title: 'Naughty Nick’s Book',
      href: 'images/gameNavBg05-icon10-4.png',
      freeTrial: true,
    },
    {
      id: 'PNG',
      title: 'Athena Ascending',
      href: 'images/gameNavBg05-icon10-5.png',
    },
    {
      id: 'PNG',
      title: 'Clash of Camelot',
      href: 'images/gameNavBg05-icon10-6.png',
      freeTrial: true,
    },
    {
      id: 'PNG',
      title: 'USA Flip',
      href: 'images/gameNavBg05-icon10-7.png',
      freeTrial: true,
    },
    {
      id: 'PNG',
      title: 'Rise of Olympus 100',
      href: 'images/gameNavBg05-icon10-8.png',
      freeTrial: true,
    },
    {
      id: 'PNG',
      title: 'CANINE CARNAGE',
      href: 'images/gameNavBg05-icon10-9.png',
      freeTrial: true,
    },
    {
      id: 'PNG',
      title: 'Count Jokula',
      href: 'images/gameNavBg05-icon10-10.png',
      freeTrial: true,
    },
  ],
  HB: [
    {
      id: 'HB',
      title: 'Tuk Tuk Thailand',
      href: 'images/gameNavBg05-icon11-1.png',
      freeTrial: true,
    },
    {
      id: 'HB',
      title: 'Taiko Beats',
      href: 'images/gameNavBg05-icon11-2.png',
    },
    {
      id: 'HB',
      title: 'Laughing Buddha',
      href: 'images/gameNavBg05-icon11-3.png',
      freeTrial: true,
    },
    {
      id: 'HB',
      title: 'Space Goonz',
      href: 'images/gameNavBg05-icon11-4.png',
      freeTrial: true,
    },
    {
      id: 'HB',
      title: 'Golden Unicorn Deluxe',
      href: 'images/gameNavBg05-icon11-5.png',
      freeTrial: true,
    },
    {
      id: 'HB',
      title: 'Bomb Runner',
      href: 'images/gameNavBg05-icon11-6.png',
      freeTrial: true,
    },
    {
      id: 'HB',
      title: 'Mighty Medusa',
      href: 'images/gameNavBg05-icon11-7.png',
      freeTrial: true,
    },
    {
      id: 'HB',
      title: 'Disco Beats',
      href: 'images/gameNavBg05-icon11-8.png',
      freeTrial: true,
    },
    {
      id: 'HB',
      title: 'Lantern Luck',
      href: 'images/gameNavBg05-icon11-9.png',
      freeTrial: true,
    },
    {
      id: 'HB',
      title: 'Lucky Durian',
      href: 'images/gameNavBg05-icon11-10.png',
      freeTrial: true,
    },
  ],
  CRG: [
    {
      id: 'CRG',
      title: 'Halloween',
      href: 'images/gameNavBg05-icon12-1.png',
    },
    {
      id: 'CRG',
      title: 'Amazing Circus',
      href: 'images/gameNavBg05-icon12-2.png',
    },
    {
      id: 'CRG',
      title: 'Tai Wang Si Shen',
      href: 'images/gameNavBg05-icon12-3.png',
    },
    {
      id: 'CRG',
      title: 'BreakAway',
      href: 'images/gameNavBg05-icon12-4.png',
    },
    {
      id: 'CRG',
      title: '1c dafudacai-5Treasures',
      href: 'images/gameNavBg05-icon12-5.png',
    },
    {
      id: 'CRG',
      title: '1c dafudacai-88Fortunes',
      href: 'images/gameNavBg05-icon12-6.png',
    },
    {
      id: 'CRG',
      title: '1c dafudacai-DiamondEternity',
      href: 'images/gameNavBg05-icon12-7.png',
    },
    {
      id: 'CRG',
      title: '1c dafudacai-DancingDrum',
      href: 'images/gameNavBg05-icon12-8.png',
    },
    {
      id: 'CRG',
      title: '1c dafudacai-FlowerOfRiches',
      href: 'images/gameNavBg05-icon12-9.png',
    },
    {
      id: 'CRG',
      title: 'Platinum',
      href: 'images/gameNavBg05-icon12-10.png',
    },
  ],
  KA: [
    {
      id: 'KA',
      title: 'Plague Doctor',
      href: 'images/gameNavBg05-icon13-1.png',
    },
    {
      id: 'KA',
      title: 'Great Doctor',
      href: 'images/gameNavBg05-icon13-2.png',
    },
    {
      id: 'KA',
      title: 'Oriental Beast',
      href: 'images/gameNavBg05-icon13-3.png',
    },
    {
      id: 'KA',
      title: 'Five Sound Fortune',
      href: 'images/gameNavBg05-icon13-4.png',
    },
    {
      id: 'KA',
      title: 'Lucky God',
      href: 'images/gameNavBg05-icon13-5.png',
    },
    {
      id: 'KA',
      title: 'Geisha',
      href: 'images/gameNavBg05-icon13-6.png',
    },
    {
      id: 'KA',
      title: 'Lazy Rich',
      href: 'images/gameNavBg05-icon13-7.png',
    },
    {
      id: 'KA',
      title: 'Empty City',
      href: 'images/gameNavBg05-icon13-8.png',
    },
    {
      id: 'KA',
      title: 'Wealth Toad',
      href: 'images/gameNavBg05-icon13-9.png',
    },
    {
      id: 'KA',
      title: 'Holiday Carol Lock 2 Spin',
      href: 'images/gameNavBg05-icon13-10.png',
    },
  ],
  HC: [
    {
      id: 'HC',
      title: 'LockMary',
      href: 'images/gameNavBg05-icon14-1.png',
    },
    {
      id: 'HC',
      title: 'Super Mario',
      href: 'images/gameNavBg05-icon14-2.png',
    },
    {
      id: 'HC',
      title: 'Western Cowboy',
      href: 'images/gameNavBg05-icon14-3.png',
    },
    {
      id: 'HC',
      title: 'King of Club',
      href: 'images/gameNavBg05-icon14-4.png',
    },
    {
      id: 'HC',
      title: 'Four Divine Beasts',
      href: 'images/gameNavBg05-icon14-5.png',
    },
    {
      id: 'HC',
      title: 'Blessings Coming MegaBonus',
      href: 'images/gameNavBg05-icon14-6.png',
    },
    {
      id: 'HC',
      title: 'Diamond Coming',
      href: 'images/gameNavBg05-icon14-7.png',
    },
    {
      id: 'HC',
      title: 'Zeus',
      href: 'images/gameNavBg05-icon14-8.png',
    },
    {
      id: 'HC',
      title: 'Aladdin',
      href: 'images/gameNavBg05-icon14-9.png',
    },
    {
      id: 'HC',
      title: 'Sea of Thieves',
      href: 'images/gameNavBg05-icon14-10.png',
    },
  ],
  WD: [
    {
      id: 'WD',
      title: 'Power of Sun Svarog',
      href: 'images/gameNavBg05-icon15-1.png',
      freeTrial: true,
    },
    {
      id: 'WD',
      title: 'Hot Slot™ Mystery Jackpot Joker',
      href: 'images/gameNavBg05-icon15-2.png',
      freeTrial: true,
    },
    {
      id: 'WD',
      title: '9 Coins™ Grand Gold Edition',
      href: 'images/gameNavBg05-icon15-3.png',
      freeTrial: true,
    },
    {
      id: 'WD',
      title: 'Burning Sun™',
      href: 'images/gameNavBg05-icon15-4.png',
      freeTrial: true,
    },
    {
      id: 'WD',
      title: 'Hot Slot™: Magic Pearls',
      href: 'images/gameNavBg05-icon15-5.png',
      freeTrial: true,
    },
    {
      id: 'WD',
      title: 'Hot Slot™: Magic Bombs',
      href: 'images/gameNavBg05-icon15-6.png',
      freeTrial: true,
    },
    {
      id: 'WD',
      title: '9 Coins™ 1000 Edition',
      href: 'images/gameNavBg05-icon15-7.png',
      freeTrial: true,
    },
    {
      id: 'WD',
      title: '9 Burning Stars™',
      href: 'images/gameNavBg05-icon15-8.png',
      freeTrial: true,
    },
    {
      id: 'WD',
      title: 'Sizzling Kingdom™ Bison',
      href: 'images/gameNavBg05-icon15-9.png',
      freeTrial: true,
    },
    {
      id: 'WD',
      title: 'Power of Gods™: Valhalla',
      href: 'images/gameNavBg05-icon15-10.png',
      freeTrial: true,
    },
  ],
  R88: [
    {
      id: 'R88',
      title: 'Lightning Fish',
      href: 'images/gameNavBg05-icon16-1.png',
    },
    {
      id: 'R88',
      title: 'Future Stars',
      href: 'images/gameNavBg05-icon16-2.png',
    },
    {
      id: 'R88',
      title: 'Pirate Treasure',
      href: 'images/gameNavBg05-icon16-3.png',
    },
    {
      id: 'R88',
      title: 'Lucky God of Wealth',
      href: 'images/gameNavBg05-icon16-4.png',
    },
    {
      id: 'R88',
      title: 'Fortune Dice',
      href: 'images/gameNavBg05-icon16-5.png',
    },
    {
      id: 'R88',
      title: 'Multi Mega Bingo Bonanza',
      href: 'images/gameNavBg05-icon16-6.png',
    },
    {
      id: 'R88',
      title: 'Nakee',
      href: 'images/gameNavBg05-icon16-7.png',
    },
    {
      id: 'R88',
      title: 'Enchantress',
      href: 'images/gameNavBg05-icon16-8.png',
    },
    {
      id: 'R88',
      title: 'Dragon Legend',
      href: 'images/gameNavBg05-icon16-9.png',
    },
    {
      id: 'R88',
      title: 'Big and Small',
      href: 'images/gameNavBg05-icon16-10.png',
    },
  ],
  FTG: [
    {
      id: 'FTG',
      title: 'Gold Mahjong',
      href: 'images/gameNavBg05-icon17-1.png',
    },
    {
      id: 'FTG',
      title: 'Four Wealth Creatures',
      href: 'images/gameNavBg05-icon17-2.png',
    },
    {
      id: 'FTG',
      title: 'Super Shot',
      href: 'images/gameNavBg05-icon17-3.png',
    },
    {
      id: 'FTG',
      title: 'Money Machine',
      href: 'images/gameNavBg05-icon17-4.png',
    },
    {
      id: 'FTG',
      title: 'Sahara Destiny',
      href: 'images/gameNavBg05-icon17-5.png',
    },
    {
      id: 'FTG',
      title: 'Auspicious Fortune God 2',
      href: 'images/gameNavBg05-icon17-6.png',
    },
    {
      id: 'FTG',
      title: 'Ramayana',
      href: 'images/gameNavBg05-icon17-7.png',
    },
    {
      id: 'FTG',
      title: 'God of Wealth 2',
      href: 'images/gameNavBg05-icon17-8.png',
    },
    {
      id: 'FTG',
      title: 'Flower of Riches',
      href: 'images/gameNavBg05-icon17-9.png',
    },
    {
      id: 'FTG',
      title: 'Dice',
      href: 'images/gameNavBg05-icon17-10.png',
    },
  ],
  AE: [
    {
      id: 'AE',
      title: 'EZ FA 2',
      href: 'images/gameNavBg05-icon18-1.png',
      freeTrial: true,
    },
    {
      id: 'AE',
      title: 'Rave Party',
      href: 'images/gameNavBg05-icon18-2.png',
      freeTrial: true,
    },
    {
      id: 'AE',
      title: 'Muay Thai',
      href: 'images/gameNavBg05-icon18-3.png',
      freeTrial: true,
    },
    {
      id: 'AE',
      title: 'Thai Paradise',
      href: 'images/gameNavBg05-icon18-4.png',
      freeTrial: true,
    },
    {
      id: 'AE',
      title: 'Highway King Pro',
      href: 'images/gameNavBg05-icon18-5.png',
      freeTrial: true,
    },
    {
      id: 'AE',
      title: 'Kungfu Monkey',
      href: 'images/gameNavBg05-icon18-6.png',
      freeTrial: true,
    },
    {
      id: 'AE',
      title: 'The Myth',
      href: 'images/gameNavBg05-icon18-7.png',
      freeTrial: true,
    },
    {
      id: 'AE',
      title: 'Fortune Lion',
      href: 'images/gameNavBg05-icon18-8.png',
      freeTrial: true,
    },
    {
      id: 'AE',
      title: 'Ru Yi Bang',
      href: 'images/gameNavBg05-icon18-9.png',
      freeTrial: true,
    },
    {
      id: 'AE',
      title: 'Baby Monkey 2',
      href: 'images/gameNavBg05-icon18-10.png',
      freeTrial: true,
    },
  ],
  AMBS: [
    {
      id: 'AMBS',
      title: 'Dino Gems',
      href: 'images/gameNavBg05-icon19-1.png',
    },
    {
      id: 'AMBS',
      title: 'Lucky Nangkwak',
      href: 'images/gameNavBg05-icon19-2.png',
    },
    {
      id: 'AMBS',
      title: 'Mafia Ways',
      href: 'images/gameNavBg05-icon19-3.png',
    },
    {
      id: 'AMBS',
      title: 'Veggies Bonanza',
      href: 'images/gameNavBg05-icon19-4.png',
    },
    {
      id: 'AMBS',
      title: 'Mahjong Legend',
      href: 'images/gameNavBg05-icon19-5.png',
    },
    {
      id: 'AMBS',
      title: 'Pet Ranger',
      href: 'images/gameNavBg05-icon19-6.png',
    },
    {
      id: 'AMBS',
      title: 'Lab 19 mania',
      href: 'images/gameNavBg05-icon19-7.png',
    },
    {
      id: 'AMBS',
      title: 'Cupid’s Garden',
      href: 'images/gameNavBg05-icon19-8.png',
    },
    {
      id: 'AMBS',
      title: 'Mermaid’s Market',
      href: 'images/gameNavBg05-icon19-9.png',
    },
    {
      id: 'AMBS',
      title: 'Drop Racing',
      href: 'images/gameNavBg05-icon19-10.png',
    },
  ],
  BP: [
    {
      id: 'BP',
      title: 'Astro Luck',
      href: 'images/gameNavBg05-icon20-1.png',
    },
    {
      id: 'BP',
      title: 'Ancient Stones',
      href: 'images/gameNavBg05-icon20-2.png',
    },
    {
      id: 'BP',
      title: 'Buffalo Begins',
      href: 'images/gameNavBg05-icon20-3.png',
    },
    {
      id: 'BP',
      title: 'BigBang Spin',
      href: 'images/gameNavBg05-icon20-4.png',
    },
    {
      id: 'BP',
      title: 'Book of Pharaoh',
      href: 'images/gameNavBg05-icon20-5.png',
    },
    {
      id: 'BP',
      title: 'Big Sevens Jackpot',
      href: 'images/gameNavBg05-icon20-6.png',
    },
    {
      id: 'BP',
      title: 'Cherry Bell',
      href: 'images/gameNavBg05-icon20-7.png',
    },
    {
      id: 'BP',
      title: 'Cleo’s Fortune',
      href: 'images/gameNavBg05-icon20-8.png',
    },
    {
      id: 'BP',
      title: 'Detective’s Dream',
      href: 'images/gameNavBg05-icon20-9.png',
    },
    {
      id: 'BP',
      title: 'Diamond Mask',
      href: 'images/gameNavBg05-icon20-10.png',
    },
  ],
  VT: [
    {
      id: 'VT',
      title: 'LostCityOfGold',
      href: 'images/gameNavBg05-icon21-1.png',
    },
    {
      id: 'VT',
      title: 'DJRemix',
      href: 'images/gameNavBg05-icon21-2.png',
    },
    {
      id: 'VT',
      title: 'JurassicWorld',
      href: 'images/gameNavBg05-icon21-3.png',
      freeTrial: true,
    },
    {
      id: 'VT',
      title: 'Halloween',
      href: 'images/gameNavBg05-icon21-4.png',
      freeTrial: true,
    },
    {
      id: 'VT',
      title: 'Circus',
      href: 'images/gameNavBg05-icon21-5.png',
      freeTrial: true,
    },
    {
      id: 'VT',
      title: 'TaiWangSiShen',
      href: 'images/gameNavBg05-icon21-6.png',
      freeTrial: true,
    },
    {
      id: 'VT',
      title: 'TrueBreakAway',
      href: 'images/gameNavBg05-icon21-7.png',
      freeTrial: true,
    },
    {
      id: 'VT',
      title: 'DuoFuDuoCai5Treasures',
      href: 'images/gameNavBg05-icon21-8.png',
      freeTrial: true,
    },
    {
      id: 'VT',
      title: 'DuoFuDuoCai88Fortune',
      href: 'images/gameNavBg05-icon21-9.png',
    },
    {
      id: 'VT',
      title: 'DuoFuDuoCaiDiamondEternity',
      href: 'images/gameNavBg05-icon21-10.png',
    },
  ],
  RSG: [
    {
      id: 'RSG',
      title: 'Dragon Legend',
      href: 'images/gameNavBg05-icon22-1.png',
    },
    {
      id: 'RSG',
      title: 'Caishen Fortunes',
      href: 'images/gameNavBg05-icon22-2.png',
    },
    {
      id: 'RSG',
      title: 'Rich Mahjong',
      href: 'images/gameNavBg05-icon22-3.png',
    },
    {
      id: 'RSG',
      title: 'Chin Shi Huang',
      href: 'images/gameNavBg05-icon22-4.png',
    },
    {
      id: 'RSG',
      title: 'Songkran',
      href: 'images/gameNavBg05-icon22-5.png',
    },
    {
      id: 'RSG',
      title: 'Happy Farm',
      href: 'images/gameNavBg05-icon22-6.png',
      freeTrial: true,
    },
    {
      id: 'RSG',
      title: 'Power of Thor',
      href: 'images/gameNavBg05-icon22-7.png',
    },
    {
      id: 'RSG',
      title: 'The Little Match Girl',
      href: 'images/gameNavBg05-icon22-8.png',
    },
    {
      id: 'RSG',
      title: 'Tai Chi',
      href: 'images/gameNavBg05-icon22-9.png',
    },
    {
      id: 'RSG',
      title: 'Book of Gold',
      href: 'images/gameNavBg05-icon22-10.png',
    },
  ],
  YL: [
    {
      id: 'YL',
      title: 'Gamelobby',
      href: 'images/gameNavBg05-icon23-1.png',
      freeTrial: true,
    },
    {
      id: 'YL',
      title: 'Fruit Machine',
      href: 'images/gameNavBg05-icon23-2.png',
    },
    {
      id: 'YL',
      title: 'Solo King',
      href: 'images/gameNavBg05-icon23-3.png',
    },
    {
      id: 'YL',
      title: 'Gold Shark',
      href: 'images/gameNavBg05-icon23-4.png',
    },
    {
      id: 'YL',
      title: 'Lucky Five',
      href: 'images/gameNavBg05-icon23-5.png',
    },
    {
      id: 'YL',
      title: 'Big Fish Eat Small Fish',
      href: 'images/gameNavBg05-icon23-6.png',
    },
    {
      id: 'YL',
      title: 'Shooting Dragon Gate',
      href: 'images/gameNavBg05-icon23-7.png',
    },
    {
      id: 'YL',
      title: 'Diamond Deal',
      href: 'images/gameNavBg05-icon23-8.png',
    },
    {
      id: 'YL',
      title: 'The Deep Forest Dance',
      href: 'images/gameNavBg05-icon23-9.png',
    },
    {
      id: 'YL',
      title: 'World Cup',
      href: 'images/gameNavBg05-icon23-10.png',
    },
  ],
};
